package github.com.jokereven.entity;

import java.util.Date;

public class ProjectInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.pi_id
     *
     * @mbg.generated
     */
    private Integer piId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.pi_projectName
     *
     * @mbg.generated
     */
    private String piProjectname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.pi_startDate
     *
     * @mbg.generated
     */
    private Date piStartdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.pi_endDate
     *
     * @mbg.generated
     */
    private Date piEnddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.pi_status
     *
     * @mbg.generated
     */
    private Integer piStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.acId
     *
     * @mbg.generated
     */
    private Integer acid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.pi_id
     *
     * @return the value of projectinfo.pi_id
     *
     * @mbg.generated
     */
    public Integer getPiId() {
        return piId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.pi_id
     *
     * @param piId the value for projectinfo.pi_id
     *
     * @mbg.generated
     */
    public void setPiId(Integer piId) {
        this.piId = piId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.pi_projectName
     *
     * @return the value of projectinfo.pi_projectName
     *
     * @mbg.generated
     */
    public String getPiProjectname() {
        return piProjectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.pi_projectName
     *
     * @param piProjectname the value for projectinfo.pi_projectName
     *
     * @mbg.generated
     */
    public void setPiProjectname(String piProjectname) {
        this.piProjectname = piProjectname == null ? null : piProjectname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.pi_startDate
     *
     * @return the value of projectinfo.pi_startDate
     *
     * @mbg.generated
     */
    public Date getPiStartdate() {
        return piStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.pi_startDate
     *
     * @param piStartdate the value for projectinfo.pi_startDate
     *
     * @mbg.generated
     */
    public void setPiStartdate(Date piStartdate) {
        this.piStartdate = piStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.pi_endDate
     *
     * @return the value of projectinfo.pi_endDate
     *
     * @mbg.generated
     */
    public Date getPiEnddate() {
        return piEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.pi_endDate
     *
     * @param piEnddate the value for projectinfo.pi_endDate
     *
     * @mbg.generated
     */
    public void setPiEnddate(Date piEnddate) {
        this.piEnddate = piEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.pi_status
     *
     * @return the value of projectinfo.pi_status
     *
     * @mbg.generated
     */
    public Integer getPiStatus() {
        return piStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.pi_status
     *
     * @param piStatus the value for projectinfo.pi_status
     *
     * @mbg.generated
     */
    public void setPiStatus(Integer piStatus) {
        this.piStatus = piStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.acId
     *
     * @return the value of projectinfo.acId
     *
     * @mbg.generated
     */
    public Integer getAcid() {
        return acid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.acId
     *
     * @param acid the value for projectinfo.acId
     *
     * @mbg.generated
     */
    public void setAcid(Integer acid) {
        this.acid = acid;
    }
}