package github.com.jokereven.dao;

import github.com.jokereven.entity.Applicant;
import github.com.jokereven.entity.ApplicantExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

public interface ApplicantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     */
    long countByExample(ApplicantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     */
    int deleteByExample(ApplicantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer acId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     */
    int insert(Applicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     */
    int insertSelective(Applicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     */
    List<Applicant> selectByExample(ApplicantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     */
    Applicant selectByPrimaryKey(Integer acId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Applicant record, @Param("example") ApplicantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Applicant record, @Param("example") ApplicantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Applicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Applicant record);
}