package github.com.jokereven.dao;

import github.com.jokereven.entity.Applicant;
import github.com.jokereven.entity.ApplicantExample;
import java.util.List;

import github.com.jokereven.entity.ProjectInfo;
import github.com.jokereven.entity.ProjectInfoExample;
import org.apache.ibatis.annotations.Param;

public interface ApplicantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     * 统计 Example 数量
     */
    long countByExample(ApplicantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     * 根据条件删除
     */
    int deleteByExample(ApplicantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     * 根据主键删除
     */
    int deleteByPrimaryKey(Integer acId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     * 插入
     */
    int insert(Applicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     * 选择性插入
     */
    int insertSelective(Applicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     * 通过条件查询
     */
    List<Applicant> selectByExample(ApplicantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     * 通过主键查询
     */
    Applicant selectByPrimaryKey(Integer acId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     * 选择性更新
     */
    int updateByExampleSelective(@Param("record") Applicant record, @Param("example") ApplicantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     * 通过条件更新
     */
    int updateByExample(@Param("record") Applicant record, @Param("example") ApplicantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     * 根据主键有选择的更新
     */
    int updateByPrimaryKeySelective(Applicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbg.generated
     * 通过键值更新
     */
    int updateByPrimaryKey(Applicant record);
}