package github.com.jokereven.dao;

import github.com.jokereven.entity.ProjectInfo;
import github.com.jokereven.entity.ProjectInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbg.generated
     */
    long countByExample(ProjectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbg.generated
     */
    int deleteByExample(ProjectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer piId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbg.generated
     */
    int insert(ProjectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbg.generated
     */
    int insertSelective(ProjectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbg.generated
     */
    List<ProjectInfo> selectByExample(ProjectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbg.generated
     */
    ProjectInfo selectByPrimaryKey(Integer piId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProjectInfo record, @Param("example") ProjectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProjectInfo record, @Param("example") ProjectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProjectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProjectInfo record);

    /*
     * 以上都是通过 generated 生成的单表操2333
     * */

    /**
     * 根据条件二表联查所有信息
     * **/
    List<ProjectInfo> selectProjectInfoByExample(ProjectInfoExample example);

    /**
     * 根据主键二表联查单个信息
     * */
    ProjectInfo selectProjectInfoByPrimaryKey(Integer piId);
}